// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "clinic-service",
    "version": "1"
  },
  "paths": {
    "/clinics/{petsClinicId}": {
      "get": {
        "summary": "getClinics",
        "description": "",
        "operationId": "getClinics.get.clinics/{petsClinicId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "petsClinicId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/clinics": {
      "get": {
        "summary": "getClinics",
        "description": "",
        "operationId": "getClinics.get.clinics",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "basePath": "/dev"
};