// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "ukhsa-pets-applicant-service",
    "version": "1"
  },
  "paths": {
    "/register-applicant": {
      "post": {
        "summary": "postApplicantDetails",
        "description": "",
        "operationId": "postApplicantDetails.post.register-applicant",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "basePath": "/dev"
};