export const medicalScreeningData = [
  {
    pk: "APPLICATION#b3dc3b1e-2dbf-4e91-9d2b-ca089b679baf",
    sk: "APPLICATION#MEDICAL#SCREENING",
    age: 25,
    applicationId: "b3dc3b1e-2dbf-4e91-9d2b-ca089b679baf",
    contactWithPersonWithTb: "No",
    contactWithTbDetails: "",
    createdBy: "pets.tester1@hotmail.com",
    dateCreated: "2025-04-22T10:10:37.254Z",
    haveMenstralPeriod: "No",
    historyOfConditionsUnder11: [],
    historyOfConditionsUnder11Details: "",
    historyOfPreviousTb: "No",
    physicalExaminationNotes: "No abnormalities detected. Patient appears healthy.",
    pregnant: "No",
    previousTbDetails: "",
    status: "completed",
    symptoms: [],
    symptomsOfTb: "No",
    symptomsOther: "",
  },
];
