#!/bin/bash

pnpm -r lint

branch_name=$(git symbolic-ref --short HEAD)

# Define the branch naming pattern
pattern="^((feature|hotfix)\/TBBETA-[0-9]+(-[a-z0-9-]+)?|release\/[0-9]+(\.[0-9]+)*|develop)$"

# Check if the branch name follows the convention
if [[ ! $branch_name =~ $pattern ]]; then
    echo "❌ ERROR: Branch name '$branch_name' does not follow the required convention:"
    echo "   Feature branch expected format: feature/{ticket-number}-{short-description}"
    echo "   Example: feature/TBBETA-123-add-authentication"
    echo "   Hotfix branch expected format: hotfix/{ticket-number}-{short-description}"
    echo "   Example: hotfix/TBBETA-123-fix-broken-doodad"
    echo "   Release branch expected format: release/x.x, release/x.x.x, release/x.x.x.x etc."
    echo "   Examples: release/1.0, release/2.3.4, release/9.12.234.5"
    exit 1
fi

echo "✅ Branch name '$branch_name' follows the required convention."
exit 0
