name: Run Virtuoso Plan

on:
  workflow_dispatch:
    inputs:
      plan_id:
        description: "5"
        required: true
      plan_name:
        description: "CI/CD_PETS"
        required: false
      environment_id:
        description: "98"
        required: true

jobs:
  run-virtuoso-plan:
    runs-on: ubuntu-latest

    env:
      VIRTUOSO_TOKEN: ${{ secrets.VIRTUOSOUKPRD_API_TOKEN }}
      PLAN_ID: ${{ inputs.plan_id }}
      PLAN_NAME: ${{ inputs.plan_name }}
      ENVIRONMENT_ID: ${{ inputs.environment_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Make script executable
        run: chmod +x ./scripts/execute.sh

      - name: Run Virtuoso plan
        run: ./scripts/execute.sh
